### ISSUE TITLE
Using the SQL model This model's maximum context length is 4097 tokens

### ISSUE THREAD

**Issue by eltoob** [BoxcarsAI/boxcars#88]
Hi,
I have an issue with a sql database.
Any tip or trick to get around this limitation?

**Comment by eltoob** [comment]
WOuld it be a good example of vectorization?

**Comment by eltoob** [comment]
I guess one other options here would be to simply create another "shot" and just give the list of tables and ask "based on this list of tables, which should be relevant to ask this sql request."

**Comment by francis** [comment]
@eltoob - you can reduce the tables when you create your SQL Boxcar. The parameter is `tables:` and you would give it a subset of the tables in your database. This might be enough to let you fit in under the 4k token limit. Otherwise, we could go the vector route and first find the appropriate tables, and then try to create the query.

**Comment by francis** [comment]
Let me know if you ran into any trouble here @eltoob
